name: "Build Binary for MacOS, Linux, and Windows"

on:
    push:
      branches: [ "main" ]  

concurrency:
    group: environment-${{ github.ref }}
    cancel-in-progress: true

permissions:
    id-token: write
    contents: write

jobs:
    get-version:
        name: "Get Haze Version"
        runs-on: "ubuntu-latest"

        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.20.4'

            - name: Build Haze CLI
              run: go build -o haze

            - name: Get Haze Version
              run: echo "HAZE_VERSION=$(./haze --version)" > haze-version.txt

            - name: Upload Haze Version Information
              uses: actions/upload-artifact@v1
              with:
                name: haze-version
                path: haze-version.txt

    build:
        needs: [get-version]
        name: "Build Haze Binaries"
        runs-on: "ubuntu-latest"

        defaults:
            run:
                shell: bash

        strategy:
            matrix:
                os: [darwin, linux, windows]
                arch: [arm64, amd64]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.20.4'

            - name: Build Haze CLI
              run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o haze-${{ matrix.os }}-${{ matrix.arch }}

            - name: Download Haze Version Information
              uses: actions/download-artifact@v1
              with:
                name: haze-version
            
            - name: Get Haze Version Information
              id: get-haze-version
              run: cat haze-version/haze-version.txt >> "$GITHUB_OUTPUT"

            - name: Publish Binary to Releases
              uses: svenstaro/upload-release-action@v2
              with:
                file: haze-${{ matrix.os }}-${{ matrix.arch }}
                asset_name: haze-${{ matrix.os }}-${{ matrix.arch }}
                tag: ${{ steps.get-haze-version.outputs.HAZE_VERSION }}
